新增知乎问题订阅
lilydjwg/morerssplz pull request #38
Opened 2020-11-14 04:44 UTC by Ynjxsjmh

![image](https://user-images.githubusercontent.com/40143136/99139814-fbf3fe00-2676-11eb-951a-2b6d1b6c6f4a.png)

2020-11-15 06:25 UTC, lilydjwg requested changes

2020-11-15 06:25 UTC, lilydjwg commented on morerss/zhihu_stream.py
> +   async def get(self, id):
Bad indent?

2020-11-15 06:25 UTC, lilydjwg commented on morerss/zhihu_stream.py
> +      'description': data['detail'],
`data['detail']` 可能是带链接的 HTML，直接这么放在我的预览里链接文本没有显示出来。要不要把 HTML 转成纯文本呢？

2020-11-15 07:38 UTC, Ynjxsjmh commented on morerss/zhihu_stream.py
> +   async def get(self, id):
[cd7b0ee](https://github.com/lilydjwg/morerssplz/pull/38/commits/cd7b0eeeb87ae8513bd7395555b3a833b15cc34e) 修复了该缩进错误。运行的时候竟然没提示错误。

2020-11-15 07:44 UTC, Ynjxsjmh commented on morerss/zhihu_stream.py
> +      'description': data['detail'],
不太清楚依云遇到了啥问题。这个 detail 直接是提问者关于问题的描述：

![image](https://user-images.githubusercontent.com/40143136/99179446-d50df880-2758-11eb-8686-52af9ac70ef9.png)

```
{
    "type": "question",
    "id": 22794831,
    "title": "有哪些书看完后会让人很后悔没有早看到？",
    "question_type": "normal",
    "created": 1392823616,
    "updated_time": 1393061327,
    "url": "https://www.zhihu.com/api/v4/questions/22794831",
    "detail": "“为什么不早一点看到，说不定它就改变了我的一生”？<br/><a href=\"http://www.zhihu.com/question/19771045\"class=\"internal\"> 有哪些「早读早超生」的书？http://www.zhihu.com/question/19771045</a>",
    "relationship": { }
}
```

提问者对问题进行说明，那么 detail 就有内容；没有说明就没内容。

请教一下依云是咋预览这个 description 的，我 Android 的 Feedly 和 Arch 上的 QuiteRSS 好像都找不到预览这个 description 的地方。

2020-11-15 07:55 UTC, lilydjwg commented on morerss/zhihu_stream.py
> +      'description': data['detail'],
我用的这个 https://addons.mozilla.org/zh-CN/firefox/addon/rsspreview/

2020-11-15 07:56 UTC, lilydjwg commented on morerss/zhihu_stream.py
> +   async def get(self, id):
因为 Python 并不禁止你缩进一个和三个空格呀，只要对齐了它都接受。

2020-11-15 08:20 UTC, Ynjxsjmh commented on morerss/zhihu_stream.py
> +      'description': data['detail'],
> https://addons.mozilla.org/zh-CN/firefox/addon/rsspreview/

这个插件真不错，已经用上了

上面的预览如下：

![image](https://user-images.githubusercontent.com/40143136/99179858-5024de00-275c-11eb-936d-0eedf2c4fd8e.png)

> `data['detail']` 可能是带链接的 HTML，直接这么放在我的预览里~~链接文本没有显示出来~~链接另起一行了，样式比较容易混淆。要不要把 HTML 转成纯文本呢？

这个 `detail` 是 HTML 格式的，如果把 HTML 转成纯文本，那么这个链接就无法点击了。

这个 `detail` 里其实还可能有图片，比如这个[问题](https://www.zhihu.com/question/60494395)，用 RSSPreview 预览如下：

![image](https://user-images.githubusercontent.com/40143136/99180088-4e5c1a00-275e-11eb-8b44-e2c7ed764f48.png)



依云有啥建议呢？

2020-11-15 12:03 UTC, Ynjxsjmh commented on morerss/zhihu_stream.py
> +      'description': data['detail'],
突然发现我干了一件蠢事，因为 `from nicelogger import enable_pretty_logging` 这一段在我机器上报错，所以我都是注释起来了，然后 commit 的时候不 track 这几行改变。但是一个星期前估计搞忘了，把注释也 track 了进去。请问我该怎么办呢？真是对不起。

![image](https://user-images.githubusercontent.com/40143136/99184371-465fa280-277d-11eb-958f-d8bad2a0760c.png)

2020-11-16 07:00 UTC, lilydjwg commented on morerss/zhihu_stream.py
> +      'description': data['detail'],
那个随它去吧，测试用的代码。

2020-11-16 07:01 UTC, lilydjwg commented
已经合并了，把最后一个提交 fixup 了一下。

2020-11-16 07:01 UTC, closed without merging